version: '2'
.catalog:
  name: "icmp zookeeper"
  version: "3.4.8"
  description: "zookeeper"
services:
  zookeeper:
    scale: 3
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 2181
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000

      