version: '2'
services:
  node-exporter:
    image: winhong/node-exporter:latest
    stdin_open: true
    network_mode: host
    tty: true
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.dns: 'true'
  grafana:
    image: winhong/grafana
    tty: true
    links:
    - prometheus:prometheus
    - prometheus-rancher-exporter:prometheus-rancher-exporter
    volumes_from:
    - graf-db
    ports:
    - 3000:3000/tcp
    labels:
      io.rancher.sidekicks: graf-db
      io.rancher.scheduler.affinity:host_label: usage=monitor
  rancher-server-ip:
    image: rancher/external-service
    labels:
      io.rancher.scheduler.affinity:host_label: usage=monitor
  cadvisor:
    image: winhong/cadvisor:latest
    stdin_open: true
    network_mode: host
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    tty: true
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.dns: 'true'
  prometheus-rancher-exporter:
    image: winhong/prometheus-rancher-exporter:v0.22.52
    tty: true
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.affinity:host_label: usage=monitor
  prometheus:
    image: winhong/prometheus
    volumes:
    - /data/
    - /root/prometheus.yml:/root/prometheus.yml
    tty: true
    extra_hosts:
    - rancher-server:${RANCHER_SERVER}
    links:
    - node-exporter:node-exporter
    - cadvisor:cadvisor
    - prometheus-rancher-exporter:prometheus-rancher-exporter
    labels:
      io.rancher.scheduler.affinity:host_label: usage=monitor
    ports:
    - 9090:9090/tcp
    command:
    - -alertmanager.url=http://alertmanager:9093
    - -config.file=/etc/prometheus/prometheus.yml
    - -storage.local.path=/prometheus
    - -web.console.libraries=/etc/prometheus/console_libraries
    - -web.console.templates=/etc/prometheus/consoles
  graf-db:
    image: winhong/graf-db
    network_mode: none
    volumes:
    - /var/lib/grafana/
    labels:
      io.rancher.scheduler.affinity:host_label: usage=monitor
    tty: true
    links:
    - prometheus:prometheus
    - prometheus-rancher-exporter:prometheus-rancher-exporter
    command:
    - cat
