oracle:
  labels:
    io.rancher.scheduler.affinity:host_label: cloud=demo
  environment:
    ORACLE_ALLOW_REMOTE: true
  restart: always
  tty: true
  image: winhong/btpserver-oracle-xe-11g:v1
  stdin_open: true
btpserver:
  labels:
    io.rancher.scheduler.affinity:host_label: cloud=demo
  restart: always
  tty: true
  image: winhong/btpserver:v3
  links:
   - 'oracle:oracle'
  stdin_open: true
btpserverlb:
  labels:
    io.rancher.scheduler.affinity:host_label: cloud=demo
  ports:
  - ${public_port}:9898
  restart: always
  tty: true
  image: rancher/load-balancer-service
  links:
  - btpserver:btpserver
  stdin_open: true
