Keepalived:
  labels:
    io.rancher.scheduler.global: 'true'
  environment:
    VIRTUAL_IP: "${virtual_ip}"
    CHECK_PORT: "${check_port}"
    VRID: 150
    INTERFACE: "${network_interface}"
    NETMASK_BIT: "${netmask_bit}"
  tty: true
  image: 192.168.200.190:5002/winhong/cibkeepalived:v1
  stdin_open: true
  net: host
  cap_add:
    - NET_ADMIN
    - NET_BROADCAST
